export const STATES = [
  'Alabama',
  'Alaska',
  'Arizona',
  'Arkansas',
  'California',
  'Colorado',
  'Connecticut',
  'Delaware',
  'Dist.Columbia',
  'Florida',
  'Georgia',
  'Hawaii',
  'Idaho',
  'Illinois',
  'Indiana',
  'Iowa',
  'Kansas',
  'Kentucky',
  'Louisiana',
  'Maine',
  'Maryland',
  'Massachusetts',
  'Michigan',
  'Minnesota',
  'Mississippi',
  'Missouri',
  'Montana',
  'Nebraska',
  'Nevada',
  'New Hampshire',
  'New Jersey',
  'New Mexico',
  'North Carolina',
  'North Dakota',
  'Ohio',
  'Oklahoma',
  'Oregon',
  'Pennsylvania',
  'Rhode Island',
  'South Carolina',
  'South Dakota',
  'Tennessee',
  'Texas',
  'Utah',
  'Vermont',
  'Virginia',
  'Washington',
  'West Virginia',
  'Wisconsin',
  'Wyoming',
];

export const RELATIONSHIP_OPTIONS = [
  'Spouse',
  'Child',
  'Parent',
  'Sibling',
  'Grandparent',
  'Grandchild',
  'Fiancé/Fiancée',
  'Domestic Partner',
  'Cousin',
  'Aunt',
  'Uncle',
  'Niece',
  'Nephew',
  'Friend',
  'Legal Guardian',
  'Business Partner',
  'Trust',
  'Estate',
  'Charity',
  'Other',
];

export const CARRIER_PRODUCTS = {
  Aetna: ['Whole Life'],
  Aflac: ['Final Expense'],
  'American Amicable': [
    'Family Protector',
    'Home Protector',
    'Safe Care Term',
    'Secure Life',
    'Senior/Family Choice',
    'Term Made Simple',
    'XUL',
  ],
  'American Home Life': ['FE'],
  Americo: ['Eagle Select', 'HMS 125', 'IUL', 'Term 100'],
  Ameritas: ['CLEAR EDGE TERM', 'IUL'],
  'Baltimore Life': ['iProvide', 'aPriority'],
  CICA: ['Allegiant Standard', 'Allegiant Guaranteed'],
  'Combined by Chubb': [
    'Preferred Final Expense',
    'Standard Final Expense',
    'Graded Final Expense',
  ],
  Corebridge: ['GIWL', 'SIWL'],
  'Columbus Life': ['IUL'],
  Ethos: [
    'Ameritas IUL',
    'Ameritas SI Term',
    'JH ROP',
    'LGA Prime',
    'TruStage GAWL',
    'TruStage SITL',
    'TruStage TAWL',
  ],
  Foresters: [
    'Advantage Plus II',
    'Bright Future Childrens WL',
    'Planright FEX',
    'Prepared II ADB',
    'Smart UL',
    'Strong Foundation',
    'Your Term',
  ],
  'Illinois Mutual': ['Final Expense'],
  InstaBrain: ['Term Life', 'Whole Life'],
  'Kansas City Life': ['SIGNATURE TERM', 'SIGNATURE TERM ROP'],
  Ladder: ['TERM'],
  LGA: ['Quility Term'],
  'Liberty Bankers Insurance Group': [
    'FLEX 4 LIFE WL PAID AT AGE 100',
    'FLEX 4 LIFE WL PAID IN 10 YEARS',
    'MODIFIED WL',
    'SIMPLIFIED ISSUE MARKET FE',
  ],
  'Mutual of Omaha': [
    'Accidental Death',
    "Children's Whole Life",
    'Final Expense',
    'IUL',
    'IULE',
    'Term Life Answers',
    'Term Life Express',
  ],
  NLG: ['Term', 'Universal Life'],
  'North American': [
    'BUILDER PLUS 3',
    'PROTECTION BUILDER IUL',
    'SMART BUILDER 2 IUL',
  ],
  'Pekin Life': ['Transitional Term'],
  'Royal Neighbors of America': [
    'FEX',
    'FEX GRADED',
    'FEX GUARANTEED ISSUE',
    'JET TERM',
    'JET WHOLE LIFE',
    'JET YOUTH WHOLE LIFE',
  ],
  SBLI: ['FEX Level Death Benefit'],
  Transamerica: ['FE', 'UL', 'Term'],
  'United Home Life': [
    'Final Expense',
    'Provider Whole Life',
    'Term',
    'Protector AD',
  ],
};

const SNACKBAR_BASE = {
  autoHideDuration: 4000,
  anchorOrigin: { vertical: 'bottom', horizontal: 'right' },
  style: {
    backgroundColor: '#FFFFFF',
    color: '#1C1A17',
    fontFamily: `"Libre Baskerville", serif`,
    fontSize: '0.875rem',
    fontWeight: 400,
    boxShadow: '0px 4px 16px rgba(0,0,0,0.08)',
    borderRadius: '4px',
    padding: '10px 16px',
  },
};

export const SNACKBAR_SUCCESS_OPTIONS = {
  ...SNACKBAR_BASE,
  style: {
    ...SNACKBAR_BASE.style,
    borderLeft: '3px solid #3F6F5B',
  },
};

export const SNACKBAR_ERROR_OPTIONS = {
  ...SNACKBAR_BASE,
  style: {
    ...SNACKBAR_BASE.style,
    borderLeft: '3px solid #8B2E2E',
  },
};
